# Generated by Django 4.0.3 on 2024-03-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_busroute_allocated_bus_number'),
        ('mainapp', '0002_register_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('seat_number', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.busroute')),
            ],
        ),
    ]
