# Generated by Django 4.0.3 on 2024-03-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bus_route',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
