# Generated by Django 4.0.3 on 2024-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_busroute_buses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
    ]
