# Generated by Django 4.0.3 on 2024-03-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_bus_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='allocated_bus_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
