# Generated by Django 4.0.3 on 2024-03-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_busroute_allocated_bus_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='allocated_bus_number',
        ),
    ]
